"""intelligence runs artifacts correlations

Revision ID: 4bd235c589d2
Revises: e1dfb83d651b
Create Date: 2026-10-07 12:45:27.452298

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd235c589d2'
down_revision: str | None = 'e1dfb83d651b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('initiated_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('artifact_count', sa.Integer(), nullable=False),
    sa.Column('correlation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'run_number', name='uq_analysis_run_number')
    )
    op.create_index(op.f('ix_analysis_runs_investigation_id'), 'analysis_runs', ['investigation_id'], unique=False)
    op.create_table('correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('correlation_type', sa.String(length=32), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('artifact_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'artifact_type', 'normalized_value', name='uq_correlation_value')
    )
    op.create_index(op.f('ix_correlations_artifact_type'), 'correlations', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_correlations_investigation_id'), 'correlations', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_correlations_normalized_value'), 'correlations', ['normalized_value'], unique=False)
    op.create_table('analysis_run_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('artifact_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'evidence_id', name='uq_run_evidence')
    )
    op.create_index(op.f('ix_analysis_run_evidence_evidence_id'), 'analysis_run_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_analysis_run_evidence_run_id'), 'analysis_run_evidence', ['run_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.String(length=500), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=False),
    sa.Column('locator', sa.JSON(), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('context', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('extractor_name', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'artifact_type', 'normalized_value', 'source_key', 'extractor_name', 'extractor_version', name='uq_artifact_identity')
    )
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_created_at'), 'artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_artifacts_evidence_id'), 'artifacts', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_artifacts_investigation_id'), 'artifacts', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_artifacts_normalized_value'), 'artifacts', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    op.create_table('correlation_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['correlation_id'], ['correlations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id', 'artifact_id', name='uq_correlation_member')
    )
    op.create_index(op.f('ix_correlation_artifacts_artifact_id'), 'correlation_artifacts', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_correlation_artifacts_correlation_id'), 'correlation_artifacts', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correlation_artifacts_correlation_id'), table_name='correlation_artifacts')
    op.drop_index(op.f('ix_correlation_artifacts_artifact_id'), table_name='correlation_artifacts')
    op.drop_table('correlation_artifacts')
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_normalized_value'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_investigation_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_evidence_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_created_at'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_analysis_run_evidence_run_id'), table_name='analysis_run_evidence')
    op.drop_index(op.f('ix_analysis_run_evidence_evidence_id'), table_name='analysis_run_evidence')
    op.drop_table('analysis_run_evidence')
    op.drop_index(op.f('ix_correlations_normalized_value'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_investigation_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_artifact_type'), table_name='correlations')
    op.drop_table('correlations')
    op.drop_index(op.f('ix_analysis_runs_investigation_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
