"""evidence verifications custody

Revision ID: e1dfb83d651b
Revises: c1de33e96662
Create Date: 2026-10-06 01:20:25.248345

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1dfb83d651b'
down_revision: str | None = 'c1de33e96662'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('evidence_number', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_by_id', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('integrity_status', sa.String(length=32), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'evidence_number', name='uq_evidence_number'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_evidence_evidence_number'), 'evidence', ['evidence_number'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_integrity_status'), 'evidence', ['integrity_status'], unique=False)
    op.create_index(op.f('ix_evidence_investigation_id'), 'evidence', ['investigation_id'], unique=False)
    op.create_table('custody_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custody_events_action'), 'custody_events', ['action'], unique=False)
    op.create_index(op.f('ix_custody_events_created_at'), 'custody_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_custody_events_evidence_id'), 'custody_events', ['evidence_id'], unique=False)
    op.create_table('evidence_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('expected_sha256', sa.String(length=64), nullable=False),
    sa.Column('observed_sha256', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_verifications_created_at'), 'evidence_verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_verifications_evidence_id'), 'evidence_verifications', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_verifications_result'), 'evidence_verifications', ['result'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_verifications_result'), table_name='evidence_verifications')
    op.drop_index(op.f('ix_evidence_verifications_evidence_id'), table_name='evidence_verifications')
    op.drop_index(op.f('ix_evidence_verifications_created_at'), table_name='evidence_verifications')
    op.drop_table('evidence_verifications')
    op.drop_index(op.f('ix_custody_events_evidence_id'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_created_at'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_action'), table_name='custody_events')
    op.drop_table('custody_events')
    op.drop_index(op.f('ix_evidence_investigation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_integrity_status'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_number'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
